---
- name: Enable CRB repository
  ansible.builtin.command:
    cmd: dnf config-manager --enable crb
  changed_when: false
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Add EPEL repository
  ansible.builtin.dnf:
    name: epel-release
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Handle virtualenv package requirements (ovos/hivemind)
  ansible.builtin.apt:
    name:
      - build-essential
      - swig
      - libfann-dev
      - libasound2-dev
      - libpulse-dev
      - libportaudio2
      - mpg123
      - music123
      - sox
      - libsox-fmt-all
      - libespeak-ng1
      - espeak-ng
      - flac
      - mpv
      - libxslt1-dev
      - libopenblas-dev
      - pkg-config
      - libicu-dev
      - portaudio19-dev
      - libjpeg-dev
    install_recommends: false
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family in ['Debian', 'Zorin OS']

- name: Handle virtualenv package requirements (ovos/hivemind)
  ansible.builtin.dnf:
    name:
      - gcc-c++
      - swig
      - fann-devel
      - alsa-lib-devel
      - pulseaudio-libs-devel
      - portaudio
      - mpg123
      - sox
      - flac
      - mpv
      - openblas-serial
      - pkgconf-pkg-config
      - libicu-devel
      - portaudio-devel
      - espeak-ng
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "RedHat"

- name: Handle virtualenv package requirements (ovos/hivemind)
  community.general.apt_rpm:
    pkg:
      - build-essential
      - swig
      - libfann-devel
      - libalsa-devel
      - libpulseaudio-devel
      - libportaudio2
      - mpg123
      - sox
      - libsox-fmt-mp3
      - libespeak-ng1
      - espeak-ng
      - flac
      - mpv
      - libxslt-devel
      - libopenblas-devel
      - pkg-config
      - libicu-devel
      - libportaudio2-devel
      - libjpeg-devel
    state: present
  when: ansible_distribution == "Altlinux"

- name: Handle virtualenv package requirements (ovos/hivemind)
  community.general.zypper:
    name:
      - gcc-c++
      - swig
      - libfann-devel
      - alsa-lib-devel
      - libpulse-devel
      - libportaudio2
      - libespeak-ng1
      - espeak-ng
      - mpg123
      - sox
      - flac
      - mpv
      - libopenblas_serial-devel
      - portaudio-devel
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "Suse"

- name: Handle virtualenv package requirements (ovos/hivemind)
  community.general.pacman:
    name:
      - base-devel
      - swig
      - alsa-lib
      - portaudio
      - mpg123
      - sox
      - flac
      - mpv
      - libxslt
      - openblas
      - espeak-ng
    state: "{{ ovos_installer_uninstall }}"
  when: ansible_os_family == "Archlinux"

- name: Handle fann package from AUR (Arch based only)
  become_user: "{{ ovos_installer_user }}"
  kewlfft.aur.aur:
    name: fann
    use: makepkg
  when: ansible_os_family == "Archlinux"
  tags:
    - skip_ansible_lint
